# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "build ipa file"
  lane :build do
    increment_build_number(xcodeproj: "example.xcodeproj")
    build_app(workspace: "example.xcworkspace", scheme: "example",export_xcargs: "-allowProvisioningUpdates")
  end
end

lane :setup do
  setup_project
end

private_lane :setup_project do
  create_keychain(
    name: "action_keychain",
    password: "meow",
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )
end






